### ISSUE TITLE
key feature is not working. 

### ISSUE THREAD

**Issue by nullhandler** [bartektartanus/pref_dessert#4]
I have two classes of `DesSer<Song>`. I have used two different keys ( overridden the get key method of `DesSer<Song>` classes ) for both of them. But the data of both are saved same.
Is this a bug?

Reference: [this class](https://github.com/OjasKarmarkar/Beats/blob/master/lib/models/BookmarkHelper.dart)
and [this class](https://github.com/OjasKarmarkar/Beats/blob/master/lib/models/RecentsHelper.dart)

**Comment by Vidar88** [comment]
The following line is shadowing the repository key:

https://github.com/bartektartanus/pref_dessert/blob/93e596b7e620163491e5308e0fa1ba4138fedaf1/lib/src/repository.dart#L83

So every entity is stored with the key "_Type".

Removing the line should fix this problem.

**Comment by bartektartanus** [comment]
Fixed in version 0.4.0 - thank you! :)

**Comment by nullhandler** [comment]
thanks. nice.
