### ISSUE TITLE
How to save only object

### ISSUE THREAD

**Issue by jackyhieu1211-hn** [bartektartanus/pref_dessert#5]
Hello admin. I use `pref_dessert `save data. 

```
repo.save(User(
        uid: user.uid,
        photoUrl: user.photoUrl,
        displayName: user.displayName,
        email: user.email));
```
And get data

`repo.findAll();`

But I want save only object. Example

`repo.save(String key, Object object)`

and get 

`repo.find(String key);`

Please add method. thank you very much.

**Comment by bartektartanus** [comment]
If you want to save only one object then you can use `SingleElementPreferencesRepository`

**Comment by jackyhieu1211-hn** [comment]
@bartektartanus thank you. 
If I want save a Object is "User". I need create DesUser. This takes a lot of time. Please optimize method. Thank you very much.

**Comment by bartektartanus** [comment]
Then you should check this package: https://pub.dev/packages/json_serializable which will allow you to generate (de)serialize methods easily.

**Comment by jackyhieu1211-hn** [comment]
thanks
